language: python
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=check
    - python: '3.6'
      env:
        - TOXENV=docs
    - env:
        - TOXENV=py36-dj111-cover,codecov,coveralls
      python: '3.6'
    - env:
        - TOXENV=py36-dj111-nocov
      python: '3.6'
    - env:
        - TOXENV=py36-dj3-cover,codecov,coveralls
      python: '3.6'
    - env:
        - TOXENV=py36-dj3-nocov
      python: '3.6'
    - env:
        - TOXENV=py37-dj111-cover,codecov,coveralls
      python: '3.7'
    - env:
        - TOXENV=py37-dj111-nocov
      python: '3.7'
    - env:
        - TOXENV=py37-dj3-cover,codecov,coveralls
      python: '3.7'
    - env:
        - TOXENV=py37-dj3-nocov
      python: '3.7'
    - env:
        - TOXENV=py38-dj111-cover,codecov,coveralls
      python: '3.8'
    - env:
        - TOXENV=py38-dj111-nocov
      python: '3.8'
    - env:
        - TOXENV=py38-dj3-cover,codecov,coveralls
      python: '3.8'
    - env:
        - TOXENV=py38-dj3-nocov
      python: '3.8'
    - env:
        - TOXENV=pypy3-dj111-cover,codecov,coveralls
        - TOXPYTHON=pypy3
      python: 'pypy3'
    - env:
        - TOXENV=pypy3-dj111-nocov
        - TOXPYTHON=pypy3
      python: 'pypy3'
    - env:
        - TOXENV=pypy3-dj3-cover,codecov,coveralls
        - TOXPYTHON=pypy3
      python: 'pypy3'
    - env:
        - TOXENV=pypy3-dj3-nocov
        - TOXPYTHON=pypy3
      python: 'pypy3'
    - env:
        - TOXENV=py35-dj111-cover,codecov,coveralls
      python: '3.5'
    - env:
        - TOXENV=py35-dj111-nocov
      python: '3.5'
    - env:
        - TOXENV=py35-dj22-cover,codecov,coveralls
      python: '3.5'
    - env:
        - TOXENV=py35-dj22-nocov
      python: '3.5'
    - env:
        - TOXENV=py27-dj111-cover,codecov,coveralls
      python: '2.7'
    - env:
        - TOXENV=py27-dj111-nocov
      python: '2.7'
    - env:
        - TOXENV=pypy-dj111-cover,codecov,coveralls
      python: 'pypy'
    - env:
        - TOXENV=pypy-dj111-nocov
      python: 'pypy'
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
install:
  - python -mpip install --progress-bar=off tox -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
