language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
    - TOXENV=2.6-1.4,coveralls,codecov
    - TOXENV=2.6-1.4-nocover
    - TOXENV=2.6-1.5,coveralls,codecov
    - TOXENV=2.6-1.5-nocover
    - TOXENV=2.6-1.6,coveralls,codecov
    - TOXENV=2.6-1.6-nocover
    - TOXENV=2.7-1.4,coveralls,codecov
    - TOXENV=2.7-1.4-nocover
    - TOXENV=2.7-1.5,coveralls,codecov
    - TOXENV=2.7-1.5-nocover
    - TOXENV=2.7-1.6,coveralls,codecov
    - TOXENV=2.7-1.6-nocover
    - TOXENV=2.7-1.7,coveralls,codecov
    - TOXENV=2.7-1.7-nocover
    - TOXENV=2.7-1.8,coveralls,codecov
    - TOXENV=2.7-1.8-nocover
    - TOXENV=3.3-1.5,coveralls,codecov
    - TOXENV=3.3-1.5-nocover
    - TOXENV=3.3-1.6,coveralls,codecov
    - TOXENV=3.3-1.6-nocover
    - TOXENV=3.3-1.7,coveralls,codecov
    - TOXENV=3.3-1.7-nocover
    - TOXENV=3.3-1.8,coveralls,codecov
    - TOXENV=3.3-1.8-nocover
    - TOXENV=3.4-1.5,coveralls,codecov
    - TOXENV=3.4-1.5-nocover
    - TOXENV=3.4-1.6,coveralls,codecov
    - TOXENV=3.4-1.6-nocover
    - TOXENV=3.4-1.7,coveralls,codecov
    - TOXENV=3.4-1.7-nocover
    - TOXENV=3.4-1.8,coveralls,codecov
    - TOXENV=3.4-1.8-nocover
    - TOXENV=pypy-1.4,coveralls,codecov
    - TOXENV=pypy-1.4-nocover
    - TOXENV=pypy-1.5,coveralls,codecov
    - TOXENV=pypy-1.5-nocover
    - TOXENV=pypy-1.6,coveralls,codecov
    - TOXENV=pypy-1.6-nocover
    - TOXENV=pypy-1.7,coveralls,codecov
    - TOXENV=pypy-1.7-nocover
    - TOXENV=pypy-1.8,coveralls,codecov
    - TOXENV=pypy-1.8-nocover
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always

